config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :twits
  resources :users do
    member do
    get 'new_profile'
    put 'update_profile'
    end
  end  

  root "twits#index"
  
  # get "twits/form"
end

app/models/twit.rb
class Twit < ApplicationRecord
    belongs_to :user
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /twits or /twits.json
  def index
    @twits = Twit.all.order("created_at DESC")
    @twit = Twit.new
  end

  # GET /twits/1 or /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = current_user.twits.build
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits or /twits.json
  def create
    @twit = current_user.twits.build(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to root_path, notice: "Twit was successfully created." }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1 or /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to twit_url(@twit), notice: "Twit was successfully updated." }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1 or /twits/1.json
  def destroy
    @twit.destroy

    respond_to do |format|
      format.html { redirect_to twits_url, notice: "Twit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twit_params
      params.require(:twit).permit(:twit)
    end
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/twits/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class= "media box">
         <figure class= "media-left">
            <p class= "image is 64x64">
                <%# <img src= "https://bulma.io/images/placeholders/64x64.png"> %>
                <%= render 'twits/user' %>
            </p>
        </figure>  
        <div class= "media-content"> 
            <%= render 'twits/form' %>
        </div>
    </article> 
    <% end %>

<%# <h1>Twits</h1> %>

<% @twits.each do | twit | %>
    <div class="box">
        <article class= "media">
            <div class= "media-left">
                <figure class= "image is-64x64">
                    <%# <img src= "https://bulma.io/images/placeholders/64x64.png"> %>
                </figure>
            </div>
            <div class= "media-content">
                <div class= "content">
                    <strong><%= twit.user.name %></strong><br/>
                    <small><%= twit.user.username %></small><br/> 

                    <p><%= twit.twit %></p>                 
                </div> 
                <nav class= "level">
                    <div class="level-left is-mobile">  
                        <%= link_to twit, class: "level-item" do %>
                        <span class= "icon"><i class="fa-solid fa-link" aria-hidden="true"> </i></span>
                        <% end %>
                        <%= link_to edit_twit_path(twit), cass: "level-item" do %>
                            <span class="icon"><i class= "fa fa-pencil" aria-hidden="true"> </i></span>
                        <% end %>    
                        <%= link_to twit, method: :delete, data: { confirm: "Are you sure you want to delete this twit?"} do %>
                            <span class="icon"><i class="fa fa-trash-o" aria-hidden= "true"> </i> </span>
                        <% end %>    
                    </div>
                </nav>
            </div>
        </article>        
    </div>
<% end %>   
</div>     

app/views/twits/_form.html.erb
<%= simple_form_for(@twit) do |f| %>
<%= f.error_notification %>
<div class= "field">
  <div class="control">
    <%= f.input :twit, label: "Twit about it", input_html: { class: "textarea" }, wrapper: false, label_html: {class:"label"}, placeholder: "Compose a new twit..." %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>    

app/views/twits/_profile.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Profile</p>
        <div class="panel-block">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <%= gravatar_image_tag(current_user.email, size:64, alt: current_user.name) %>
                        <%# <img src="https://bulma.io/images/placeholders/64x64.pnj"> %>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <strong><%= current_user.name %></strong><br />
                            <small><%= current_user.username %></small>
                            <small></small>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        <div class="panel-block">
            <div class="level is-mobile">
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Twits</p>
                        <p class="title is-6"><%= current_user.twits.count %></p>
                    </div>
                </div>    
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Following</p>
                        <p class="title is-6">123</p>
                    </div>
                </div>
                <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Followers</p>
                        <p class="title is-6">467k</p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>                                    

app/views/twits/_trends.html.erb
<div class= "column is-one-quater">
    <nav class="panel">
        <p class= "panel-heading">Trends</p>
        <a class= "panel-block">
            Trend 1
        </a>     
        <a class= "panel-block">
            Trend 2
        </a>
        <a class= "panel-block">
            Trend 3
        </a>
        <a class= "panel-block">
            Trend 4
        </a>
        <a class= "panel-block">
            Trend 5
        </a>
        <a class= "panel-block">
            Trend 6
        </a>
    </nav>
</div>        

app/views/twits/_twit.html.erb
<div id="<%= dom_id twit %>">
  <p>
    <strong>Twit:</strong>
    <%= twit.twit %>
  </p>

</div>

app/views/twits/_user.html.erb
<div id="<%= dom_id user %>"> 
    <%= user.image %>
</div>

app/views/twits/_who-to-follow.html.erb
<div class= "coloumn">
    <nav class= "panel">
        <p class= "panel-heading"> Who to Follow </p>
    
    <div class= "panel-block">
    <article class="media">
            <div class= "media-left">
                <figure class="image is 32x32">
                    <img src= "https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class= "content">
                <p>
                    <strong>Ashish Dede</strong><br/>
                    <small>@ashdede88</small>
                </p>
            </div>
            </div>
        </article>
    </div>

    <div class= "panel-block">
        <article class="media">
            <div class= "media-left">
                <figure class="image is 32x32">
                    <img src= "https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class= "content">
                <p>
                    <strong>Mahadev Chavan</strong><br/>
                    <small>@mahadu07</small>
                </p>
            </div>
            </div>
        </article>
    </div>

    <div class= "panel-block">
        <article class="media">
            <div class= "media-left">
                <figure class="image is 32x32">
                    <img src= "https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class= "content">
                <p>
                    <strong>Avadhut P</strong><br/>
                    <small>@avadhu11</small>
                </p>
            </div>
            </div>
        </article>
    </div>
</div>
</nav>
                 

app/views/twits/edit.html.erb
<h1>Editing twit</h1>

<%= render "form", twit: @twit %>

<br>

<div>
  <%= link_to "Show this twit", @twit %> |
  <%= link_to "Back to twits", twits_path %>
</div>

app/views/twits/index.html.erb
<section class= "section">
  <div class= "container">
    <div class= "columns">
      <%= render 'trends'%>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>    


<%# <p style="color: green"><%= notice</p> %>

app/views/twits/new.html.erb
<h1>New twit</h1>

<%= render "form", twit: @twit %>

<br>

<div>
  <%= link_to "Back to twits", twits_path %>
</div>

app/views/twits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twit %>

<div>
  <%= link_to "Edit this twit", edit_twit_path(@twit) %> |
  <%= link_to "Back to twits", twits_path %>

  <%= button_to "Destroy this twit", @twit, method: :delete %>
</div>