config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :twits
  resources :users do
    member do
    get 'new_profile'
    put 'update_profile'
    end
  end  

  root "twits#index"
  
  # get "twits/form"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    #CSS %>
   <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/f8d2f74695.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% if flash[:notice] %>
        <div class = "notification is-primary global-notification" >  <%# BULMA_CLASS %>
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-primary global-notification" >
          <p class="alert"><%= alert %></p>
      <% end %>

    <nav class= "navbar is-info">
      <div class= "navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-9">Twitter</h1>
        <% end %>
        <div class= "navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id = "navbarExample" class = "navbar-menu" >
        <div class="navbar-end">
          <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
            <%= link_to 'New Twit', new_twit_path, class: "button is-info is-inverted" %>
            </p>

            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to 'Sign Out', destroy_user_session_path, class: 'some-css-class', data: { turbo_method: :delete } %>
              </p>
              <p>
                <%= link_to 'Update pic', new_profile_user_path(current_user.id) %>   
              </p>
            <% else %>  
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info"%>
            </p>
              <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info"%>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </body>
</html>
<%= yield %>